include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Prefer const declarations
    prefer_const_declarations: true
    
    # Avoid unnecessary containers
    avoid_unnecessary_containers: true
    
    # Prefer sized box over container
    prefer_sized_box: true
    
    # Avoid print statements
    avoid_print: true
    
    # Prefer single quotes
    prefer_single_quotes: true
    
    # Sort child properties
    sort_child_properties_last: true
    
    # Use key in widget constructors
    use_key_in_widget_constructors: true
    
    # Avoid empty catch blocks
    avoid_empty_catches: true
    
    # Prefer final fields
    prefer_final_fields: true
    
    # Prefer final locals
    prefer_final_locals: true
    
    # Unnecessary new
    unnecessary_new: true
    
    # Unnecessary const
    unnecessary_const: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
