name: sanjeevika_app
description: A medical QR code scanning and billing application for medicine vendors and lab technicians.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  # QR Code Scanning
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # Camera
  camera: ^0.10.5+5
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # PDF Generation
  pdf: ^3.10.7
  path_provider: ^2.1.1
  
  # File Sharing
  share_plus: ^7.2.1
  
  # HTTP Requests
  http: ^1.1.0
  
  # JSON Handling
  json_annotation: ^4.8.1
  
  # Date Formatting
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
